// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flock.proto

package flockpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RaftRequest struct {
	// Types that are valid to be assigned to Request:
	//	*RaftRequest_KvQueryRequest
	//	*RaftRequest_KvTxnRequest
	//	*RaftRequest_KvCompactionRequest
	//	*RaftRequest_LeaseGrantRequest
	//	*RaftRequest_LeaseQueryRequest
	//	*RaftRequest_LeaseGetRequest
	//	*RaftRequest_LeaseRevokeRequest
	//	*RaftRequest_LeaseRenewRequest
	Request isRaftRequest_Request `protobuf_oneof:"request"`
	ID      string                `protobuf:"bytes,64,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
}

func (m *RaftRequest) Reset()         { *m = RaftRequest{} }
func (m *RaftRequest) String() string { return proto.CompactTextString(m) }
func (*RaftRequest) ProtoMessage()    {}
func (*RaftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87515fe46cf1e69, []int{0}
}
func (m *RaftRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RaftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RaftRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RaftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftRequest.Merge(m, src)
}
func (m *RaftRequest) XXX_Size() int {
	return m.Size()
}
func (m *RaftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftRequest proto.InternalMessageInfo

type isRaftRequest_Request interface {
	isRaftRequest_Request()
	MarshalTo([]byte) (int, error)
	Size() int
}

type RaftRequest_KvQueryRequest struct {
	KvQueryRequest *KVQueryRequest `protobuf:"bytes,1,opt,name=kv_query_request,json=kvQueryRequest,proto3,oneof" json:"kv_query_request,omitempty"`
}
type RaftRequest_KvTxnRequest struct {
	KvTxnRequest *KVTxnRequest `protobuf:"bytes,2,opt,name=kv_txn_request,json=kvTxnRequest,proto3,oneof" json:"kv_txn_request,omitempty"`
}
type RaftRequest_KvCompactionRequest struct {
	KvCompactionRequest *KVCompactionRequest `protobuf:"bytes,3,opt,name=kv_compaction_request,json=kvCompactionRequest,proto3,oneof" json:"kv_compaction_request,omitempty"`
}
type RaftRequest_LeaseGrantRequest struct {
	LeaseGrantRequest *LeaseGrantRequest `protobuf:"bytes,4,opt,name=lease_grant_request,json=leaseGrantRequest,proto3,oneof" json:"lease_grant_request,omitempty"`
}
type RaftRequest_LeaseQueryRequest struct {
	LeaseQueryRequest *LeaseQueryRequest `protobuf:"bytes,5,opt,name=lease_query_request,json=leaseQueryRequest,proto3,oneof" json:"lease_query_request,omitempty"`
}
type RaftRequest_LeaseGetRequest struct {
	LeaseGetRequest *LeaseGetRequest `protobuf:"bytes,6,opt,name=lease_get_request,json=leaseGetRequest,proto3,oneof" json:"lease_get_request,omitempty"`
}
type RaftRequest_LeaseRevokeRequest struct {
	LeaseRevokeRequest *LeaseRevokeRequest `protobuf:"bytes,7,opt,name=lease_revoke_request,json=leaseRevokeRequest,proto3,oneof" json:"lease_revoke_request,omitempty"`
}
type RaftRequest_LeaseRenewRequest struct {
	LeaseRenewRequest *LeaseRenewRequest `protobuf:"bytes,8,opt,name=lease_renew_request,json=leaseRenewRequest,proto3,oneof" json:"lease_renew_request,omitempty"`
}

func (*RaftRequest_KvQueryRequest) isRaftRequest_Request()      {}
func (*RaftRequest_KvTxnRequest) isRaftRequest_Request()        {}
func (*RaftRequest_KvCompactionRequest) isRaftRequest_Request() {}
func (*RaftRequest_LeaseGrantRequest) isRaftRequest_Request()   {}
func (*RaftRequest_LeaseQueryRequest) isRaftRequest_Request()   {}
func (*RaftRequest_LeaseGetRequest) isRaftRequest_Request()     {}
func (*RaftRequest_LeaseRevokeRequest) isRaftRequest_Request()  {}
func (*RaftRequest_LeaseRenewRequest) isRaftRequest_Request()   {}

func (m *RaftRequest) GetRequest() isRaftRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RaftRequest) GetKvQueryRequest() *KVQueryRequest {
	if x, ok := m.GetRequest().(*RaftRequest_KvQueryRequest); ok {
		return x.KvQueryRequest
	}
	return nil
}

func (m *RaftRequest) GetKvTxnRequest() *KVTxnRequest {
	if x, ok := m.GetRequest().(*RaftRequest_KvTxnRequest); ok {
		return x.KvTxnRequest
	}
	return nil
}

func (m *RaftRequest) GetKvCompactionRequest() *KVCompactionRequest {
	if x, ok := m.GetRequest().(*RaftRequest_KvCompactionRequest); ok {
		return x.KvCompactionRequest
	}
	return nil
}

func (m *RaftRequest) GetLeaseGrantRequest() *LeaseGrantRequest {
	if x, ok := m.GetRequest().(*RaftRequest_LeaseGrantRequest); ok {
		return x.LeaseGrantRequest
	}
	return nil
}

func (m *RaftRequest) GetLeaseQueryRequest() *LeaseQueryRequest {
	if x, ok := m.GetRequest().(*RaftRequest_LeaseQueryRequest); ok {
		return x.LeaseQueryRequest
	}
	return nil
}

func (m *RaftRequest) GetLeaseGetRequest() *LeaseGetRequest {
	if x, ok := m.GetRequest().(*RaftRequest_LeaseGetRequest); ok {
		return x.LeaseGetRequest
	}
	return nil
}

func (m *RaftRequest) GetLeaseRevokeRequest() *LeaseRevokeRequest {
	if x, ok := m.GetRequest().(*RaftRequest_LeaseRevokeRequest); ok {
		return x.LeaseRevokeRequest
	}
	return nil
}

func (m *RaftRequest) GetLeaseRenewRequest() *LeaseRenewRequest {
	if x, ok := m.GetRequest().(*RaftRequest_LeaseRenewRequest); ok {
		return x.LeaseRenewRequest
	}
	return nil
}

func (m *RaftRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RaftRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RaftRequest_KvQueryRequest)(nil),
		(*RaftRequest_KvTxnRequest)(nil),
		(*RaftRequest_KvCompactionRequest)(nil),
		(*RaftRequest_LeaseGrantRequest)(nil),
		(*RaftRequest_LeaseQueryRequest)(nil),
		(*RaftRequest_LeaseGetRequest)(nil),
		(*RaftRequest_LeaseRevokeRequest)(nil),
		(*RaftRequest_LeaseRenewRequest)(nil),
	}
}

func init() {
	proto.RegisterType((*RaftRequest)(nil), "flockpb.RaftRequest")
}

func init() { proto.RegisterFile("flock.proto", fileDescriptor_a87515fe46cf1e69) }

var fileDescriptor_a87515fe46cf1e69 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0x4f, 0x4f, 0xfa, 0x30,
	0x18, 0x07, 0xf0, 0x8d, 0xdf, 0x0f, 0x90, 0x62, 0x50, 0x0a, 0xc4, 0x05, 0xcd, 0x42, 0x3c, 0x71,
	0xc2, 0x44, 0xcf, 0x26, 0x06, 0x88, 0x7f, 0x22, 0x89, 0xb1, 0x31, 0x5e, 0x97, 0xb1, 0x14, 0x42,
	0x3a, 0xd7, 0x51, 0x4a, 0xc5, 0xb3, 0x6f, 0xc0, 0x97, 0xe5, 0x91, 0xa3, 0x47, 0x03, 0x6f, 0xc4,
	0xac, 0x5b, 0xda, 0x6d, 0x70, 0x6b, 0xbf, 0x7d, 0xf6, 0xc9, 0xf3, 0x3c, 0x19, 0xa8, 0x4e, 0x7c,
	0xea, 0x91, 0x5e, 0xc8, 0x28, 0xa7, 0xb0, 0x2c, 0x2f, 0xe1, 0xb8, 0xdd, 0x9c, 0xd2, 0x29, 0x95,
	0xd9, 0x45, 0x74, 0x8a, 0x9f, 0xdb, 0x15, 0x16, 0x7a, 0xf1, 0xf1, 0xfc, 0xb3, 0x08, 0xaa, 0xc8,
	0x9d, 0x70, 0x84, 0xe7, 0x4b, 0xbc, 0xe0, 0x70, 0x00, 0x8e, 0x89, 0x70, 0xe6, 0x4b, 0xcc, 0x3e,
	0x1c, 0x16, 0x67, 0x96, 0xd9, 0x31, 0xbb, 0xd5, 0xcb, 0x93, 0x5e, 0x82, 0xf6, 0x1e, 0x5f, 0x9f,
	0xa3, 0xf7, 0xe4, 0x93, 0x7b, 0x03, 0xd5, 0x88, 0x48, 0x27, 0xf0, 0x1a, 0xd4, 0x88, 0x70, 0xf8,
	0x2a, 0x50, 0x44, 0x41, 0x12, 0xad, 0x14, 0xf1, 0xb2, 0x0a, 0x34, 0x70, 0x48, 0x84, 0xbe, 0x43,
	0x04, 0x5a, 0x44, 0x38, 0x1e, 0x7d, 0x0b, 0x5d, 0x8f, 0xcf, 0xa8, 0x56, 0xfe, 0x49, 0xe5, 0x2c,
	0xa5, 0x0c, 0x54, 0x91, 0xc6, 0x1a, 0x44, 0xec, 0xc4, 0x70, 0x04, 0x1a, 0x3e, 0x76, 0x17, 0xd8,
	0x99, 0x32, 0x37, 0xe0, 0x4a, 0xfc, 0x2f, 0xc5, 0xb6, 0x12, 0x47, 0x51, 0xcd, 0x5d, 0x54, 0xa2,
	0xbd, 0xba, 0x9f, 0x0f, 0xb5, 0x96, 0x5d, 0x54, 0x71, 0x9f, 0x96, 0xdb, 0x55, 0xac, 0x65, 0xd6,
	0x75, 0x0b, 0xea, 0x49, 0x6f, 0x58, 0x77, 0x56, 0x92, 0x96, 0x95, 0xeb, 0x0c, 0xa7, 0xfa, 0x3a,
	0xf2, 0xb3, 0x11, 0x7c, 0x02, 0xcd, 0xd8, 0x61, 0x58, 0x50, 0x82, 0x15, 0x55, 0x96, 0xd4, 0x69,
	0x96, 0x42, 0xb2, 0x46, 0x6b, 0xd0, 0xdf, 0x49, 0xf5, 0x98, 0x0c, 0x07, 0xf8, 0x5d, 0x79, 0x07,
	0xfb, 0xc6, 0x44, 0x51, 0x49, 0x7e, 0xcc, 0x74, 0x08, 0x6b, 0xa0, 0xf0, 0x30, 0xb4, 0x6e, 0x3a,
	0x66, 0xb7, 0x82, 0x0a, 0xb3, 0x61, 0xbf, 0x02, 0xca, 0x89, 0xd8, 0xb7, 0xbe, 0x37, 0xb6, 0xb9,
	0xde, 0xd8, 0xe6, 0xef, 0xc6, 0x36, 0xbf, 0xb6, 0xb6, 0xb1, 0xde, 0xda, 0xc6, 0xcf, 0xd6, 0x36,
	0xc6, 0x25, 0xf9, 0x9b, 0x5e, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x03, 0x07, 0x87, 0xde, 0xdf,
	0x02, 0x00, 0x00,
}

func (m *RaftRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RaftRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintFlock(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0x82
	}
	if m.Request != nil {
		{
			size := m.Request.Size()
			i -= size
			if _, err := m.Request.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *RaftRequest_KvQueryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_KvQueryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KvQueryRequest != nil {
		{
			size, err := m.KvQueryRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_KvTxnRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_KvTxnRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KvTxnRequest != nil {
		{
			size, err := m.KvTxnRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_KvCompactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_KvCompactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KvCompactionRequest != nil {
		{
			size, err := m.KvCompactionRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_LeaseGrantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_LeaseGrantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeaseGrantRequest != nil {
		{
			size, err := m.LeaseGrantRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_LeaseQueryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_LeaseQueryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeaseQueryRequest != nil {
		{
			size, err := m.LeaseQueryRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_LeaseGetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_LeaseGetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeaseGetRequest != nil {
		{
			size, err := m.LeaseGetRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_LeaseRevokeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_LeaseRevokeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeaseRevokeRequest != nil {
		{
			size, err := m.LeaseRevokeRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *RaftRequest_LeaseRenewRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RaftRequest_LeaseRenewRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeaseRenewRequest != nil {
		{
			size, err := m.LeaseRenewRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	return len(dAtA) - i, nil
}
func encodeVarintFlock(dAtA []byte, offset int, v uint64) int {
	offset -= sovFlock(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RaftRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		n += m.Request.Size()
	}
	l = len(m.ID)
	if l > 0 {
		n += 2 + l + sovFlock(uint64(l))
	}
	return n
}

func (m *RaftRequest_KvQueryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KvQueryRequest != nil {
		l = m.KvQueryRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_KvTxnRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KvTxnRequest != nil {
		l = m.KvTxnRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_KvCompactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KvCompactionRequest != nil {
		l = m.KvCompactionRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_LeaseGrantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeaseGrantRequest != nil {
		l = m.LeaseGrantRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_LeaseQueryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeaseQueryRequest != nil {
		l = m.LeaseQueryRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_LeaseGetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeaseGetRequest != nil {
		l = m.LeaseGetRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_LeaseRevokeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeaseRevokeRequest != nil {
		l = m.LeaseRevokeRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}
func (m *RaftRequest_LeaseRenewRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeaseRenewRequest != nil {
		l = m.LeaseRenewRequest.Size()
		n += 1 + l + sovFlock(uint64(l))
	}
	return n
}

func sovFlock(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFlock(x uint64) (n int) {
	return sovFlock(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RaftRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RaftRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RaftRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvQueryRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KVQueryRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_KvQueryRequest{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvTxnRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KVTxnRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_KvTxnRequest{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvCompactionRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KVCompactionRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_KvCompactionRequest{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseGrantRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LeaseGrantRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_LeaseGrantRequest{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseQueryRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LeaseQueryRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_LeaseQueryRequest{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseGetRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LeaseGetRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_LeaseGetRequest{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseRevokeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LeaseRevokeRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_LeaseRevokeRequest{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseRenewRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LeaseRenewRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &RaftRequest_LeaseRenewRequest{v}
			iNdEx = postIndex
		case 64:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlock
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFlock(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFlock
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFlock
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFlock
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFlock
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFlock        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFlock          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFlock = fmt.Errorf("proto: unexpected end of group")
)
